### ISSUE TITLE
No such file or directory in bin_resolver (image_optim 0.21)

### ISSUE THREAD

**Issue by jesson** [toy/image_optim#109]
```
/home/csolg/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/fileutils.rb:704:in `lstat': No such file or directory @ rb_file_s_lstat - /tmp/d20151006-690-1tppxay (Errno::ENOENT)
	from /home/csolg/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/fileutils.rb:704:in `remove_entry_secure'
	from /home/csolg/.rvm/gems/ruby-2.2.3/gems/image_optim-0.21.0/lib/image_optim/bin_resolver.rb:123:in `block in symlink_custom_bin!'
	from /home/csolg/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/csolg/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```
it appears after run any command in Rails

My solve doesn't work
``` ruby
      unless @dir
        @dir = FSPath.temp_dir
        at_exit{ FileUtils.remove_entry_secure @dir  if File.exists? @dir}
      end
```

**Comment by jesson** [comment]
Sorry, version from github works for me.

**Comment by toy** [comment]
Strange as there is no change in bin_resolver.rb from tag v0.21. But a reminder that I should release new version :)
