### ISSUE TITLE
incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by srghma** [toy/image_optim#159]
I skip this error?

```
✗ 0.061131559s jpeg-recompress --quality veryhigh --no-copy ./2014/09/DavidStoll1.jpg /tmp/DavidStoll120180515-1-6eh4pe.jpg
✗ 0.065645288s jpeg-recompress --quality veryhigh --no-copy ./2014/09/DavidStoll1-300x266.jpg /tmp/DavidStoll1-300x26620180515-1-cdfro2.jpg
✓ 0.014096505s jpegoptim --max\=85 --strip-all --quiet -- /tmp/DavidStoll1-300x26620180515-1-cdfro2.jpg
✓ 0.031819458s jpegoptim --max\=85 --strip-all --quiet -- /tmp/DavidStoll120180515-1-6eh4pe.jpg
✓ 0.115182547s jpegrescan -s /tmp/ChildMigrant120180515-1-1b5n00g.jpg /tmp/ChildMigrant120180515-1-kuzn3r.jpg
optimizing:   3.3% (ETA: 2.7h)✗ 0.018941255s jpeg-recompress --quality veryhigh --no-copy ./2014/09/Douthat_New-articleInline1-100x150.jpg /tmp/Douthat_New-articleInline1-100x15020180515-1-bwb27i.jpg
✓ 0.007820673s jpegoptim --max\=85 --strip-all --quiet -- /tmp/Douthat_New-articleInline1-100x15020180515-1-bwb27i.jpg
✗ 0.149456237s jpeg-recompress --quality veryhigh --no-copy ./2014/09/DavidStoll1-450x372.jpg /tmp/DavidStoll1-450x37220180515-1-cpb435.jpg
✗ 0.050220077s jpeg-recompress --quality veryhigh --no-copy ./2014/09/Douthat_New-articleInline1.jpg /tmp/Douthat_New-articleInline120180515-1-yp16po.jpg
✓ 0.01312179s jpegoptim --max\=85 --strip-all --quiet -- /tmp/Douthat_New-articleInline120180515-1-yp16po.jpg
✓ 0.088365442s jpegrescan -s ./2014/09/DavidStoll1-300x266.jpg /tmp/DavidStoll1-300x26620180515-1-cdfro2.jpg
✓ 0.055697767s jpegrescan -s ./2014/09/Douthat_New-articleInline1-100x150.jpg /tmp/Douthat_New-articleInline1-100x15020180515-1-bwb27i.jpg
✓ 0.035176298s jpegoptim --max\=85 --strip-all --quiet -- /tmp/DavidStoll1-450x37220180515-1-cpb435.jpg
✓ 0.12509118s jpegrescan -s ./2014/09/DavidStoll1.jpg /tmp/DavidStoll120180515-1-6eh4pe.jpg
✓ 0.058071197s jpegrescan -s ./2014/09/Douthat_New-articleInline1.jpg /tmp/Douthat_New-articleInline120180515-1-yp16po.jpg
✓ 0.093857551s jpegrescan -s ./2014/09/DavidStoll1-450x372.jpg /tmp/DavidStoll1-450x37220180515-1-cpb435.jpg
optimizing:   3.3% (elapsed: 5.6m)
incompatible character encodings: UTF-8 and ASCII-8BIT
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim/worker.rb:131:in `execute'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim/worker/jpegrecompress.rb:43:in `optimize'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:112:in `block (4 levels) in optimize_image'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim/handler.rb:41:in `process'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:111:in `block (3 levels) in optimize_image'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:110:in `each'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:110:in `block (2 levels) in optimize_image'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim/handler.rb:25:in `for'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:109:in `block in optimize_image'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim/cache.rb:24:in `fetch'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:108:in `optimize_image'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:126:in `optimize_image!'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:246:in `block in run_method_for'
/usr/local/bundle/gems/progress-3.4.0/lib/progress/with_progress.rb:101:in `block (3 levels) in run_with_length'
/usr/local/bundle/gems/progress-3.4.0/lib/progress.rb:80:in `step'
/usr/local/bundle/gems/progress-3.4.0/lib/progress/class_methods.rb:25:in `step'
/usr/local/bundle/gems/progress-3.4.0/lib/progress/with_progress.rb:100:in `block (2 levels) in run_with_length'
/usr/local/bundle/gems/in_threads-1.5.0/lib/in_threads.rb:290:in `block (4 levels) in runner_thread'
/usr/local/bundle/gems/in_threads-1.5.0/lib/in_threads.rb:204:in `catch'
/usr/local/bundle/gems/in_threads-1.5.0/lib/in_threads.rb:290:in `block (3 levels) in runner_thread'
/usr/local/bundle/gems/in_threads-1.5.0/lib/in_threads.rb:178:in `block (2 levels) in initialize'

```

and I cant find exact image, that causes an error, because the image is processed first, then outputted to log (to show execution time as I understand)

**Comment by toy** [comment]
Limiting number of threads to 1 can help pin point the image (`--no-threads` for CLI or `threads: false` in config or options).
Looking at [line 131 of worker.rb](https://github.com/toy/image_optim/blob/v0.26.1/lib/image_optim/worker.rb#L131) it seems that encoding error can come only from cmd_args, can you please add a debugging line `puts cmd_args.map{ |arg| [arg.inspect, arg.encoding] }` before line 131?

**Comment by srghma** [comment]
```
"jpeg-recompress"
US-ASCII
"--quality"
UTF-8
"veryhigh"
UTF-8
"--no-copy"
UTF-8
"./2014/09/Do\xC3\xB1aCatarina1-150x100.jpg"
ASCII-8BIT
"/tmp/Do\xC3\xB1aCatarina1-150x10020180516-347-16o9ta3.jpg"
ASCII-8BIT
optimizing:   3.3% (elapsed: 13.8m)
incompatible character encodings: UTF-8 and ASCII-8BIT
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim/worker.rb:132:in `execute'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim/worker/jpegrecompress.rb:43:in `optimize'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:112:in `block (4 levels) in optimize_image'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim/handler.rb:41:in `process'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:111:in `block (3 levels) in optimize_image'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:110:in `each'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:110:in `block (2 levels) in optimize_image'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim/handler.rb:25:in `for'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:109:in `block in optimize_image'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim/cache.rb:24:in `fetch'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:108:in `optimize_image'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:126:in `optimize_image!'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:246:in `block in run_method_for'
/usr/local/bundle/gems/progress-3.4.0/lib/progress/with_progress.rb:101:in `block (3 levels) in run_with_length'
/usr/local/bundle/gems/progress-3.4.0/lib/progress.rb:80:in `step'
/usr/local/bundle/gems/progress-3.4.0/lib/progress/class_methods.rb:25:in `step'
/usr/local/bundle/gems/progress-3.4.0/lib/progress/with_progress.rb:100:in `block (2 levels) in run_with_length'
/usr/local/bundle/gems/progress-3.4.0/lib/progress/with_progress.rb:99:in `map'
/usr/local/bundle/gems/progress-3.4.0/lib/progress/with_progress.rb:99:in `block in run_with_length'
/usr/local/bundle/gems/progress-3.4.0/lib/progress/class_methods.rb:16:in `start'
/usr/local/bundle/gems/progress-3.4.0/lib/progress/with_progress.rb:98:in `run_with_length'
/usr/local/bundle/gems/progress-3.4.0/lib/progress/with_progress.rb:68:in `run'
/usr/local/bundle/gems/progress-3.4.0/lib/progress/with_progress.rb:45:in `method_missing'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:245:in `run_method_for'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:159:in `optimize_images!'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim/runner.rb:76:in `optimize_images!'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim/runner.rb:62:in `run!'
/usr/local/bundle/gems/image_optim-0.26.1/bin/image_optim:20:in `<top (required)>'
/usr/local/bundle/bin/image_optim:23:in `load'
/usr/local/bundle/bin/image_optim:23:in `<main>'
```

**Comment by srghma** [comment]
https://files.fm/u/8h3bbhn8

**Comment by srghma** [comment]
`      cmd_args = [bin, *arguments].map(&:to_s).map { |s| s.force_encoding('UTF-8') }`


helps

**Comment by toy** [comment]
It is not about the content of the file, but about its name containing multibyte character and it been sent with wrong encoding. It looks like your environment lacks variable to set encoding, so while file paths as arguments contain UTF-8 code points, they have encoding set to binary.

Try to run:
```shell
ruby -e 'p *ARGV.map{ |arg| [arg, arg.encoding] }' 2014/09/*
```

Also check output of command `locale`.

Simple fix is to set `LC_ALL="en_GB.UTF-8"` where "en_GB" can be replaced with any other locale.

**Comment by srghma** [comment]
Setting locale works

```
  docker run -it --rm \
    -v $PWD:/usr/src/app \
    -w /usr/src/app ruby:2.4-stretch bash -c \
    "gem install image_optim image_optim_pack && \
    (curl -L \"http://static.jonof.id.au/dl/kenutils/pngout-20150319-linux.tar.gz\" | tar -xz -C /usr/bin --strip-components 2 --wildcards \"*/x86_64/pngout\") && \
    bash"
```

```
root@135ada4b1858:/usr/src/app# echo $LC_ALL

root@fd0ad552aa24:/usr/src/app# ruby -e 'p *ARGV.map{ |arg| [arg, arg.encoding] }' 2014/09/* | grep -C 3 Cata
["2014/09/DavidStoll1.jpg", #<Encoding:US-ASCII>]
["2014/09/Douthat_New-articleInline1-100x150.jpg", #<Encoding:US-ASCII>]
["2014/09/Douthat_New-articleInline1.jpg", #<Encoding:US-ASCII>]
["2014/09/Do\xC3\xB1aCatarina1-150x100.jpg", #<Encoding:ASCII-8BIT>]
["2014/09/Do\xC3\xB1aCatarina1-300x200.jpg", #<Encoding:ASCII-8BIT>]
["2014/09/Do\xC3\xB1aCatarina1.jpg", #<Encoding:ASCII-8BIT>]
["2014/09/Dr-Farid-Fata-pleads-guilty-victims-families-still-want-justice1-1024x576.jpg", #<Encoding:US-ASCII>]
["2014/09/Dr-Farid-Fata-pleads-guilty-victims-families-still-want-justice1-1038x576.jpg", #<Encoding:US-ASCII>]
["2014/09/Dr-Farid-Fata-pleads-guilty-victims-families-still-want-justice1-150x84.jpg", #<Encoding:US-ASCII>]


root@fd0ad552aa24:/usr/src/app# image_optim --no-threads --verbose 2014/09/DoñaCatarina1.jpg 
image_optim v0.26.1
config:
  threads: false
  verbose: true
nice: 10
threads: 1
pack: true
skip_missing_workers: true
allow_lossy: false
cache_dir: 
cache_worker_digests: false
image_optim_pack: all bins from /usr/local/bundle/gems/image_optim_pack-0.5.0.20180419-x86_64-linux/vendor/linux-x86_64 worked
Resolved pngcrush 1.8.13 at /usr/local/bundle/gems/image_optim_pack-0.5.0.20180419-x86_64-linux/vendor/linux-x86_64/pngcrush
Resolved pngout 20150319 at /usr/bin/pngout
Resolved advpng 2.1 at /usr/local/bundle/gems/image_optim_pack-0.5.0.20180419-x86_64-linux/vendor/linux-x86_64/advpng
Resolved optipng 0.7.7 at /usr/local/bundle/gems/image_optim_pack-0.5.0.20180419-x86_64-linux/vendor/linux-x86_64/optipng
Resolved pngquant 2.11.7 at /usr/local/bundle/gems/image_optim_pack-0.5.0.20180419-x86_64-linux/vendor/linux-x86_64/pngquant
Resolved jhead 3.00 at /usr/local/bundle/gems/image_optim_pack-0.5.0.20180419-x86_64-linux/vendor/linux-x86_64/jhead
Resolved jpegtran 9c at /usr/local/bundle/gems/image_optim_pack-0.5.0.20180419-x86_64-linux/vendor/linux-x86_64/jpegtran
Resolved jpegoptim 1.4.6 at /usr/local/bundle/gems/image_optim_pack-0.5.0.20180419-x86_64-linux/vendor/linux-x86_64/jpegoptim
Resolved jpegrescan 1a762f62 at /usr/local/bundle/gems/image_optim-0.26.1/vendor/jpegrescan
Resolved gifsicle 1.91 at /usr/local/bundle/gems/image_optim_pack-0.5.0.20180419-x86_64-linux/vendor/linux-x86_64/gifsicle
svgo worker: `svgo` not found; please provide proper binary or disable this worker (--no-svgo argument or `:svgo => false` through options)
Workers by format:
jpeg:
  jhead:
  jpegoptim:
    allow_lossy: false
    strip: ["all"]
    max_quality: 100
  jpegtran:
    copy_chunks: false
    progressive: true
    jpegrescan: true
png:
  pngcrush:
    chunks: ["alla"]
    fix: false
    brute: false
    blacken: true
  optipng:
    level: 6
    interlace: false
    strip: true
  pngquant:
    allow_lossy: false
    max_colors: 256
    quality: 100..100
    speed: 3
  pngout:
    copy_chunks: false
    strategy: 0
  advpng:
    level: 4
gif:
  gifsicle:
    interlace: false
    level: 3
    careful: false
  gifsicle:
    interlace: true
    level: 3
    careful: false
- is not a file or a directory or does not exist
optimizing: ...... (elapsed: 0s)
incompatible character encodings: UTF-8 and ASCII-8BIT
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim/worker.rb:131:in `execute'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim/worker/jpegoptim.rb:57:in `optimize'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:112:in `block (4 levels) in optimize_image'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim/handler.rb:41:in `process'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:111:in `block (3 levels) in optimize_image'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:110:in `each'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:110:in `block (2 levels) in optimize_image'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim/handler.rb:25:in `for'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:109:in `block in optimize_image'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim/cache.rb:24:in `fetch'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:108:in `optimize_image'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:126:in `optimize_image!'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:246:in `block in run_method_for'
/usr/local/bundle/gems/progress-3.4.0/lib/progress/with_progress.rb:101:in `block (3 levels) in run_with_length'
/usr/local/bundle/gems/progress-3.4.0/lib/progress.rb:80:in `step'
/usr/local/bundle/gems/progress-3.4.0/lib/progress/class_methods.rb:25:in `step'
/usr/local/bundle/gems/progress-3.4.0/lib/progress/with_progress.rb:100:in `block (2 levels) in run_with_length'
/usr/local/bundle/gems/progress-3.4.0/lib/progress/with_progress.rb:99:in `map'
/usr/local/bundle/gems/progress-3.4.0/lib/progress/with_progress.rb:99:in `block in run_with_length'
/usr/local/bundle/gems/progress-3.4.0/lib/progress/class_methods.rb:16:in `start'
/usr/local/bundle/gems/progress-3.4.0/lib/progress/with_progress.rb:98:in `run_with_length'
/usr/local/bundle/gems/progress-3.4.0/lib/progress/with_progress.rb:68:in `run'
/usr/local/bundle/gems/progress-3.4.0/lib/progress/with_progress.rb:45:in `method_missing'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:245:in `run_method_for'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim.rb:159:in `optimize_images!'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim/runner.rb:76:in `optimize_images!'
/usr/local/bundle/gems/image_optim-0.26.1/lib/image_optim/runner.rb:62:in `run!'
/usr/local/bundle/gems/image_optim-0.26.1/bin/image_optim:20:in `<top (required)>'
/usr/local/bundle/bin/image_optim:23:in `load'
/usr/local/bundle/bin/image_optim:23:in `<main>'
root@fd0ad552aa24:/usr/src/app# export LC_ALL=en_US.UTF-8
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
root@fd0ad552aa24:/usr/src/app# export LC_ALL=C.UTF-8     
root@fd0ad552aa24:/usr/src/app# image_optim --no-threads --verbose 2014/09/DoñaCatarina1.jpg 
image_optim v0.26.1
config:
  threads: false
  verbose: true
nice: 10
threads: 1
pack: true
skip_missing_workers: true
allow_lossy: false
cache_dir: 
cache_worker_digests: false
image_optim_pack: all bins from /usr/local/bundle/gems/image_optim_pack-0.5.0.20180419-x86_64-linux/vendor/linux-x86_64 worked
Resolved pngcrush 1.8.13 at /usr/local/bundle/gems/image_optim_pack-0.5.0.20180419-x86_64-linux/vendor/linux-x86_64/pngcrush
Resolved pngout 20150319 at /usr/bin/pngout
Resolved advpng 2.1 at /usr/local/bundle/gems/image_optim_pack-0.5.0.20180419-x86_64-linux/vendor/linux-x86_64/advpng
Resolved optipng 0.7.7 at /usr/local/bundle/gems/image_optim_pack-0.5.0.20180419-x86_64-linux/vendor/linux-x86_64/optipng
Resolved pngquant 2.11.7 at /usr/local/bundle/gems/image_optim_pack-0.5.0.20180419-x86_64-linux/vendor/linux-x86_64/pngquant
Resolved jhead 3.00 at /usr/local/bundle/gems/image_optim_pack-0.5.0.20180419-x86_64-linux/vendor/linux-x86_64/jhead
Resolved jpegtran 9c at /usr/local/bundle/gems/image_optim_pack-0.5.0.20180419-x86_64-linux/vendor/linux-x86_64/jpegtran
Resolved jpegoptim 1.4.6 at /usr/local/bundle/gems/image_optim_pack-0.5.0.20180419-x86_64-linux/vendor/linux-x86_64/jpegoptim
Resolved jpegrescan 1a762f62 at /usr/local/bundle/gems/image_optim-0.26.1/vendor/jpegrescan
Resolved gifsicle 1.91 at /usr/local/bundle/gems/image_optim_pack-0.5.0.20180419-x86_64-linux/vendor/linux-x86_64/gifsicle
svgo worker: `svgo` not found; please provide proper binary or disable this worker (--no-svgo argument or `:svgo => false` through options)
Workers by format:
jpeg:
  jhead:
  jpegoptim:
    allow_lossy: false
    strip: ["all"]
    max_quality: 100
  jpegtran:
    copy_chunks: false
    progressive: true
    jpegrescan: true
png:
  pngcrush:
    chunks: ["alla"]
    fix: false
    brute: false
    blacken: true
  optipng:
    level: 6
    interlace: false
    strip: true
  pngquant:
    allow_lossy: false
    max_colors: 256
    quality: 100..100
    speed: 3
  pngout:
    copy_chunks: false
    strategy: 0
  advpng:
    level: 4
gif:
  gifsicle:
    interlace: false
    level: 3
    careful: false
  gifsicle:
    interlace: true
    level: 3
    careful: false
optimizing: ......✓ 0.014748407s jpegoptim --strip-all --quiet -- /tmp/Do\ñaCatarina120180517-215-1c5iuno.jpg
✓ 0.132244008s jpegrescan -s 2014/09/Do\ñaCatarina1.jpg /tmp/Do\ñaCatarina120180517-215-1c5iuno.jpg
optimizing: 100.0% (elapsed: 0s)
------         2014/09/DoñaCatarina1.jpg
Total: ------       
```

**Comment by toy** [comment]
As the problem is in encoding of arguments, I think there is nothing to do about it in `image_optim`, what do you think?

**Comment by srghma** [comment]
@toy I agree, one can easily find and resolve this issue by setting `LC_ALL="en_GB.UTF-8"`, closing, tnx for all
