### ISSUE TITLE
Unable to skip missing workers

### ISSUE THREAD

**Issue by murkfletcher** [toy/image_optim#91]
**config/initializers/paperclip_optimizer.rb**
```rb

Paperclip::PaperclipOptimizer.default_options = {
  skip_missing_workers: true,
  advpng: false,
  gifsicle: false,
  jhead: false,
  jpegoptim: false,
  jpegrecompress: false,
  jpegtran: false,
  optipng: false,
  pngcrush: false,
  pngout: false,
  pngquant: false,
  svgo: false
}
```

Result:
```
=> Booting Puma
=> Rails 4.2.0 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Unknown architecture (openbsd5.7) assuming one processor.
Exiting
/usr/local/lib/ruby/gems/2.2/gems/image_optim-0.21.0/lib/image_optim/worker/class_methods.rb:72:in `create_all': Bin resolving errors: (ImageOptim::BinResolver::Error)
pngout worker: `pngout` not found; please provide proper binary or disable this worker (--no-pngout argument or `:pngout => false` through options)
advpng worker: `advpng` not found; please provide proper binary or disable this worker (--no-advpng argument or `:advpng => false` through options)
pngquant worker: `pngquant` not found; please provide proper binary or disable this worker (--no-pngquant argument or `:pngquant => false` through options)
jpegoptim worker: `jpegoptim` not found; please provide proper binary or disable this worker (--no-jpegoptim argument or `:jpegoptim => false` through options)
svgo worker: `svgo` not found; please provide proper binary or disable this worker (--no-svgo argument or `:svgo => false` through options)
        from /usr/local/lib/ruby/gems/2.2/gems/image_optim-0.21.0/lib/image_optim/worker/class_methods.rb:44:in `create_all_by_format'
        from /usr/local/lib/ruby/gems/2.2/gems/image_optim-0.21.0/lib/image_optim.rb:77:in `initialize'
        from /usr/local/lib/ruby/gems/2.2/gems/image_optim-0.21.0/lib/image_optim/railtie.rb:26:in `new'
        from /usr/local/lib/ruby/gems/2.2/gems/image_optim-0.21.0/lib/image_optim/railtie.rb:26:in `register_preprocessor'
        from /usr/local/lib/ruby/gems/2.2/gems/image_optim-0.21.0/lib/image_optim/railtie.rb:7:in `block in <class:Railtie>'
        from /usr/local/lib/ruby/gems/2.2/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
        from /usr/local/lib/ruby/gems/2.2/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
        from /usr/local/lib/ruby/gems/2.2/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /usr/local/lib/ruby/2.2/tsort.rb:226:in `block in tsort_each'
        from /usr/local/lib/ruby/2.2/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/lib/ruby/2.2/tsort.rb:429:in `each_strongly_connected_component_from'
        from /usr/local/lib/ruby/2.2/tsort.rb:347:in `block in each_strongly_connected_component'
        from /usr/local/lib/ruby/2.2/tsort.rb:345:in `each'
        from /usr/local/lib/ruby/2.2/tsort.rb:345:in `call'
        from /usr/local/lib/ruby/2.2/tsort.rb:345:in `each_strongly_connected_component'
        from /usr/local/lib/ruby/2.2/tsort.rb:224:in `tsort_each'
        from /usr/local/lib/ruby/2.2/tsort.rb:203:in `tsort_each'
        from /usr/local/lib/ruby/gems/2.2/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
        from /usr/local/lib/ruby/gems/2.2/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
        from /usr/local/lib/ruby/gems/2.2/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `public_send'
        from /usr/local/lib/ruby/gems/2.2/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `method_missing'
        from /home/dev/myapp/config/environment.rb:5:in `<top (required)>'
        from /usr/local/lib/ruby/gems/2.2/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/lib/ruby/gems/2.2/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/local/lib/ruby/gems/2.2/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/lib/ruby/gems/2.2/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
        from /home/dev/myapp/config.ru:3:in `block in <main>'
        from /usr/local/lib/ruby/gems/2.2/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
        from /usr/local/lib/ruby/gems/2.2/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
        from /home/dev/myapp/config.ru:in `new'
        from /home/dev/myapp/config.ru:in `<main>'
        from /usr/local/lib/ruby/gems/2.2/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
        from /usr/local/lib/ruby/gems/2.2/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
        from /usr/local/lib/ruby/gems/2.2/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
        from /usr/local/lib/ruby/gems/2.2/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
        from /usr/local/lib/ruby/gems/2.2/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
        from /usr/local/lib/ruby/gems/2.2/gems/railties-4.2.0/lib/rails/commands/server.rb:61:in `app'
        from /usr/local/lib/ruby/gems/2.2/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
        from /usr/local/lib/ruby/gems/2.2/gems/railties-4.2.0/lib/rails/commands/server.rb:139:in `log_to_stdout'
        from /usr/local/lib/ruby/gems/2.2/gems/railties-4.2.0/lib/rails/commands/server.rb:78:in `start'
        from /usr/local/lib/ruby/gems/2.2/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:80:in `block in server'
        from /usr/local/lib/ruby/gems/2.2/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `tap'
        from /usr/local/lib/ruby/gems/2.2/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `server'
        from /usr/local/lib/ruby/gems/2.2/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /usr/local/lib/ruby/gems/2.2/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:8:in `require'
        from bin/rails:8:in `<main>'
```

**Comment by murkfletcher** [comment]
Wrong repo, sorry.

**Comment by toy** [comment]
Though `Unknown architecture (openbsd5.7) assuming one processor.` should be fixed :)
